### ISSUE TITLE
Preferred tactic for template/style collaboration?

### ISSUE THREAD

**Issue by joeldebruijn** [xot/ssst#17]
I've got SSST working on my test-server, which is a personal milestone so to say.
But before I get in to migrating from 8 to 625 posts ....

**Background:**

- The template files in this repo are a bit 'bare-bones' and I started to do little tweaks.
- Responsive layout is missing, so there is no 'content-choreography' for small sites.
- I took a look at blog.xot.nl and the templates/stylesheets used. It responds very well while decreasing browser width etc.

**Ways to collaborate on style/layout**
What do you prefer?

- Leaving the repo as it is?
- Creating sub-directories for every template fileset in the template folder? Maybe rename the current template fileset to "SSST Classic"?
- Creating a second repo for templates alone?
- Would you mind if your current template on xot also was public with an MIT license? 
- Or a version of it with other colors and stuff, to have xot stay unique?

Easiest for me would be to have your html/css as a starting point and change colors etc, but not without consent.

**Comment by xot** [comment]
Feel free to use my ccs/html for your blog; restyling and recoloring would be appreciated ;-) But I feel no need to make to public.

The templates and ccs in the ssst repository are bare bones on purpose, so should not really be edited. I could add a subdirectory 'contributed-templates' for contributions.

**Comment by joeldebruijn** [comment]
Thank you!
