### ISSUE TITLE
SSST-Add error: Post xyz does not exist

### ISSUE THREAD

**Issue by joeldebruijn** [xot/ssst#4]
When given the command (to start with a new article):

python3 ssst-add --source '/home/path/to/Source' --verbosity -1 'TestPost2.md' 

it just returns

ssst-add: error: Post TestPost2.md does not exist.

Omitting file extension doesnt make a difference.

**Comment by joeldebruijn** [comment]
Ah ok!

So the workflow for a new post is iiuc?

- Create the folders in a structure resembling the desired permalink, if not already in place. e.g. year-month-daynumber.
- Create a md file with title as filename or copy from a template markdown file (for yaml headers etc).
- Type away
- Switch to terminal, cd to this directory.
- ssst-add

**Comment by joeldebruijn** [comment]
So, the original md file ' somewhere'  doesnt even need to be in the source tree?
But on the other hand, when it is in the source tree I do need to have some subfolders I guess?
Otherwise I have multiple files named index.md? (If I use "Path/Title/index.md" instead of Path/titel.md)

**Comment by joeldebruijn** [comment]
One way I tried:

1. I create a testPost.md in the root of the source path
2. Open terminal with source directory as active directory
3. Run python3 ssst-add --source '/path-to/Source' 'TestPost.md'

Will give:
"python3: can't open file '/path-to/Source/ssst-add': [Errno 2] No such file or directory" 

Does it add the command itself after the path?

**Comment by xot** [comment]
The command line option for `ssst` is `-s` not `-source`.

**Comment by xot** [comment]
If you run python3 in a folder that does not contain ssst-add you have to specify the full path to ssst-add (the error message complains it cannot find ssst-add, and by the looks of it you run python3 in /path-to/Source/TestPost/ )

**Comment by joeldebruijn** [comment]
Ah that got rid of the "Post xyz does not exist"!

But then I get this instead:
ssst-add: error: Aux tree aux does not exist.

Thanks for your patience with this, I got ssst itself working fine, very fast even so.
Just ssst-add wont work.

If I understand correctly: 
- ssst traverses all folders and files converting them to html
- ssst-add only generates the html for one post and the new versions of the needed index pages?

So can I just use ssst without ever using ssst-add? Only downside it generates the whole site again? 
Or does ssst also ignore 'untouched'  files? So it wont even slow down very much when the site contains like 900 posts?

**Comment by xot** [comment]
No, asst-add is a tool to add post stored anywhere on disk at the right place within the directory tree storing your blog (ie it copies not somewhere within the path specified by -s).

ssst-add needs access to the aux-tree as well (to check for known categories and tags) so this must be specified on the commandline as well (using -a)

**Comment by joeldebruijn** [comment]
Ah thanks!
Made a documentation edit for this as well.
