### ISSUE TITLE
Template: Bare bones by design or am doing something wrong?

### ISSUE THREAD

**Issue by joeldebruijn** [xot/ssst#5]
When given the command

python3 ssst --source '/home/path/to/Source' --aux '/home/path/to/Aux' --destination '/home/path/to/Destination' --templates '/home/path/to/Templates'

and uploading the destinations folders to htttps:/test.blogisch.nl it shows a very bare bones styled site.
![afbeelding](https://github.com/xot/ssst/assets/3906940/7bfc7dcc-a5eb-4554-a503-d7f9d236a584)

I looked at the css files and I think it checks out (just blue headings and sans-serif etc) but wanted to be sure:
Is it supposed to look this for starters? Because then I will study CSS etc.

**Comment by joeldebruijn** [comment]
Just to add, the html produced has this 

<link rel="stylesheet" href="./ssst-homepage.css">

but the destination folder doesnt have any css files.

Do I need to upload it seperately?

**Comment by xot** [comment]
You have to add them separately. The repository provides a set of CSS files as bare bones setup, in the templates directory. With the current templates, the CSS files should be in the root of the public folder. That is not really nice. I will commit a patch soon so the are expected to be in the ./css folder in the root of the public folder.

**Comment by xot** [comment]
Patch now committed.

**Comment by joeldebruijn** [comment]
Thanx!
