### ISSUE TITLE
Performance: never returning to command prompt

### ISSUE THREAD

**Issue by joeldebruijn** [xot/ssst#6]
I used "python3 ssst --source etc" to build the site.

Fairly quick it generates the index.html of the homepage but after that my fan starts spinning and .... nothing happens.
Let it run for half an hour but it never ends. Had to close the terminal to stop it.

Now this could be caused by numerous things I guess. My use python out of the box as provided by Debian.

But just to ask  if there is a direction in which I can check to pinpoint this issue?

**Comment by joeldebruijn** [comment]
The resulting output stops at # Determining all obsolete files from /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Destination

# Scanning posts and pages.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Source/index.md.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Source/2024/02/25/TestPost.md.
# Generating auxiliary data files.
- Processing 2 in the source tree.
- 1 posts and 1 pages.
# Generating tag files.
--- Dumping to /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/markdown/index.sst.
--- Dumping to /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/self-hosted/index.sst.
--- Dumping to /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/static/index.sst.
# Generating category files.
--- Dumping to /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/category/documentation/index.sst.
# Generating archive files.
--- Dumping to /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/2024/02/index.sst.
# Scanning auxiliary files.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/archives.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tags.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/categories.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/static/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/markdown/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/self-hosted/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/2024/02/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/category/documentation/index.sst.
# Determining items to make...
-- Considering index.md for work.
-- Considering 2024/02/25/TestPost.md for work.
- Found 1 work items in source tree.
-- Considering archives.sst for work.
-- Considering tags.sst for work.
-- Considering categories.sst for work.
-- Considering tag/static/index.sst for work.
-- Considering tag/markdown/index.sst for work.
-- Considering tag/self-hosted/index.sst for work.
-- Considering 2024/02/index.sst for work.
-- Considering category/documentation/index.sst for work.
- Found 0 work items in auxiliary tree.
# Found 1 items to make.
# Making items...
# Making home page.
-- Processing equations.
# Making RSS feed.
-- Processing equations.
# Determining all obsolete files from /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Destination

**Comment by joeldebruijn** [comment]
Ghe the hashtag of the output gets rendered as markdown

**Comment by joeldebruijn** [comment]
# Scanning posts and pages.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Source/index.md.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Source/2024/02/25/TestPost.md.
# Generating auxiliary data files.
- Processing 2 in the source tree.
- 1 posts and 1 pages.
# Generating tag files.
# Generating category files.
# Generating archive files.
# Scanning auxiliary files.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/archives.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tags.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/categories.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/static/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/markdown/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/tag/self-hosted/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/2024/02/index.sst.
-- Processing item /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Aux/category/documentation/index.sst.
# Determining items to make...
-- Considering index.md for work.
-- Considering 2024/02/25/TestPost.md for work.
- Found 1 work items in source tree.
-- Considering archives.sst for work.
-- Considering tags.sst for work.
-- Considering categories.sst for work.
-- Considering tag/static/index.sst for work.
-- Considering tag/markdown/index.sst for work.
-- Considering tag/self-hosted/index.sst for work.
-- Considering 2024/02/index.sst for work.
-- Considering category/documentation/index.sst for work.
- Found 0 work items in auxiliary tree.
# Found 1 items to make.
# Making items...
# Making home page.
-- Processing equations.
# Making RSS feed.
-- Processing equations.
# Determining all obsolete files from /home/joeldebruijn/S/Joel/SysOp/Websites/nl.blogisch.test/Destination

**Comment by joeldebruijn** [comment]
Does verbosity 2 produce the same result in this case?

**Comment by joeldebruijn** [comment]
If I force stop it, I get:

^CTraceback (most recent call last):
  File "/usr/lib/python3.11/pathlib.py", line 574, in _cparts
    return self._cached_cparts
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_cached_cparts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joeldebruijn/N/Joel/SysOp/Software/Jaap-Henk Hoepman - SSST/ssst", line 1533, in <module>
    deleted += delete_obsolete_dst_files(src_items,aux_items)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joeldebruijn/N/Joel/SysOp/Software/Jaap-Henk Hoepman - SSST/ssst", line 385, in delete_obsolete_dst_files
    while prefix != Path('.'):
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 582, in __eq__
    return self._cparts == other._cparts and self._flavour is other._flavour
                           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 576, in _cparts
    self._cached_cparts = self._flavour.casefold_parts(self._parts)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 258, in casefold_parts
    def casefold_parts(self, parts):

KeyboardInterrupt

**Comment by xot** [comment]
Ouch... Yes that's a bug alright ;-) Fixed now with latest commit

**Comment by joeldebruijn** [comment]
Thanks!!
