### ISSUE TITLE
Hard coded links to pages?

### ISSUE THREAD

**Issue by joeldebruijn** [xot/ssst#8]
Are links to pages (on the homepage) added manually?

As I intend to keep them to a minimum this wouldnt be a problem, but to be certain:
Links to pages are added in ssst-homepage.html?

For example at line 31: 
![afbeelding](https://github.com/xot/ssst/assets/3906940/23158221-5e4c-4956-9e99-6e3aa0d7b94a)

The about page seems to be added manually.

If so I will create them there also.

**Comment by xot** [comment]
Yes. ssst creates a summary of the most recent posts and adds them automatically to the homepage. It also creates archive pages, tag pages and category pages based on the content of posts. (For ssst, pages are any .md files it  encounters without a category and a tag; everything else is a post). Any references to page must be added manually to the output, for example by editing the templates, or adding links to pages from other pages or posts.
